### ISSUE TITLE
Control Property Documentation Needs to be Auto-Generated

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/avalonia-docs#229]
It's taking a lot of time to document (copy/paste) control properties that are already in source code. This needs to be an automated process somehow similar to what Microsoft does.

 1. Automating is extremely fast
 2. Automating ensures no desync between the docs and source code: The source is the single source of truth
 3. Forces better API documentation in code.

Documentation will need to handle summary, remarks and references correctly.

Also see the discussion here:
 * https://github.com/AvaloniaUI/Avalonia/discussions/11198

**Comment by stevemonaco** [comment]
Adding some DocFX experiment issues here.

In regards to filtering:
* Controls can inherit hundreds of members. DocFX can filter these members, but some are useful: `Button` members on a `ToggleButton` doc. Some are never useful: `object` members.
* `[PrivateApi]` and `Impl` interfaces need to be hidden. Can be done with filtering.

General issues:
* Which repo should own the generated docs?
* Which repo should run the workload to generate the docs. If not Avalonia itself, then the workload needs to clone the repo.
* Need to avoid building Avalonia itself. DocFX seems to want to do this, but maybe it's just my config.
* How to integrate with existing docs? DocFX outputs YML files for each type, so a React component could be created to parse+add listings to various pages.
* How to integrate with existing docs search? Algolia crawls the docs site weekly to generate this. Probably not worth it.

DocFX Filter file (for reference):
```yaml
apiRules:

# [PrivateApi}
- exclude:
    hasAttribute:
      uid: Avalonia.Metadata.PrivateApiAttribute
# Impl
- exclude:
    uidRegex: Impl$
    type: Interface
# object members
- exclude:
    uidRegex: ^System\.Object
    type: Type
```
